google/docsy-example

README.md, config.toml, content/en/docs/Getting started/_index.md
Fixed some links to the draft theme repo
=> Update repo names

content/en/_index.html
@LisaFC please take a look : )
=> Fixing broken link to example repository.

README.md
This is very difficult to find otherwise.
=> Linking to the staged website from the README.

config.toml
`images` will not work unless they are under `[params]`.
=> Move images to params.images

config.toml
Add a param for Algolia docsearch, related to PR on Docsy theme https://github.com/google/docsy/pull/127/
=> Update config.toml with Algolia Docsearch param

config.toml
As requested in https://github.com/google/docsy/pull/142/files#r338549380
=> Adding offlineSearch param

package-lock.json, package.json
+ Update dev dependencies to latest versions. (I confirmed that running `hugo server` and viewing the site works as expected.)
+ Fix URLs in package file.
Fixes #45.
=> update package.json and package-lock.json

content/en/blog/news/second-post.md, content/en/blog/releases/in-depth-monoliths-detailed-spec.md, content/en/docs/Getting started/_index.md, content/en/docs/Getting started/example-page.md, content/en/docs/Reference/parameter-reference.md, content/en/docs/Tasks/Ponycopters/_index.md, content/en/docs/Tasks/Ponycopters/configuring-ponycopters.md, content/en/docs/Tasks/Ponycopters/launching-ponycopters.md, content/en/docs/Tasks/beds.md, content/en/docs/Tasks/task.md, content/en/docs/Tutorials/multi-bear.md, content/en/docs/Tutorials/tutorial2.md
fixing descripton to description
=> fixing typo

config.toml
relates to https://github.com/google/docsy/pull/325/
=> Add config param for prism

README.md
Small improvement to the Docker section of the README
=> Geriom readme fixes

config.toml
Fixes https://github.com/google/docsy/issues/479
=> Update search engine

config.toml
Followup to https://github.com/google/docsy/pull/702
=> Add navbar_translucent_over_cover_disable and sort ui elements

config.toml
=> Flip incorrect boolean in comment

.gitignore
=> Bumped docsy theme to latest version

config.toml
=> config.toml: replace tabs with whitespace

netlify.toml
This PR updates docsy theme submodule to latest version 1d126ab1bbf186fa, thus closing #163.
=> Updating docsy theme submodule

Dockerfile
This fixes the following issue #179
=> Add /src to git safe.directory

README.md, go.mod, go.sum, netlify.toml
This PR updates the example site to latest released docsy version 0.5.1.
=> Update docsy theme to dosy version v0.5.1

package.json
This PR corrects outdated license information in `package.json`. It also corrects some minor details on the way.
=> Correct license information

README.md
=> Drop warning at the start of the README (#222)

package.json
(indirectly)
- Closes #245 (which I missed to notice before I created this PR 🤷🏼‍♂️)
=> Upgrade to Hugo 0.120.4, which include security patch

package.json
=> package.json: use local cross-env

content/no/docs/content-management/tutorials/in-depth-microservices-the-core-concepts.md
- Followup to #235
- Adds back the space between the front-matter keyword and the string that follows it.
Without the space, Hugo sees `title:"Detaljert om mikroservicer:` as the key and `De grunnleggende konseptene"` as its value.
---
Here's an example of the fix in the generated site files:
```console
$ (cd public && git diff -bw --ignore-blank-lines) | tail -500 | head 
...
```
```diff
+++ b/no/docs/cloud-computing/tutorials/the-inside-of-go-the-inner-workings/index.html
@@ -155,7 +155,7 @@
<li class="td-sidebar-nav__section-title td-sidebar-nav__section without-child" id="m-nodocscontent-managementtutorialsthe-inside-of-recursion-the-inner-workings-li">
<a href="/no/docs/content-management/tutorials/the-inside-of-recursion-the-inner-workings/" title="Innsiden av rekursjon: Drivverket" …
```
=> Front-matter title fix: revert space deletion

package.json
=> [CI] Add script to help update NPM pkgs, and update pkgs

go.mod, go.sum
=> Upgrade Docsy to 0.11.0

content/en/blog/news/second-post.md, content/en/blog/releases/in-depth-monoliths-detailed-spec.md
=> Replace broken image links

content/en/blog/news/first-post/index.md
=> First blog post: fix display of listing inside code block
