google/docsy-example

content/en/blog/news/second-post.md, content/en/blog/releases/in-depth-monoliths-detailed-spec.md
Changing these placekitten links to https so Netlify doesn't give mixed-content warnings (ahead of Docsy workshop next week at OSCON). SSL kittens for everyone! 😺
=> Changing placekitten links to be https

config.toml
I needed a way to disable the About link in the footer and discovered this option by looking in the code. It's working for my site using the Docsy theme so I thought other people might benefit from knowing about it.
=> Add config option for about link in footer

package-lock.json
GitHub's security feature informed me that some of the deps needed a bump.
This patch was created by `npm audit fix`.
Partially fixes https://github.com/google/docsy/issues/140 npm audit did not take care of the `mem` package.
=> Bump packages with CVEs

content/en/search-index.md
The `content/en/search-index.md` is no longer needed for local search.
=> Remove a unnecessary file

config.toml
Turn on the "print entire section" feature that was pushed to Docsy.
Not sure how this is deployed, but might need to check it's using a relatively recent version of Hugo to deploy successfully.
=> Update docsy theme & enable 'print entire section'

README.md, dev.Dockerfile
Docker image to run docsy-example locally without having to install all the dependencies.
=> Add Docker image to run docsy-example locally

Dockerfile, README.md, dev.Dockerfile, docker-compose.yaml
Add Dockerfile for building with the latest and the docker-compose, building the site and running. The current version of the `Dockerfile` does not work! It fails... the container stops because of an error... 
Instead of using the `Dockerfile`, we introduced a new Dockerfile with a different docker image with the latest version.
* I think this is due to using an older version of `hugo`... 
```console
$ docker build -f dev.Dockerfile -t docsy-example-dev:latest .
...
...
=> => naming to docker.io/library/docsy-example-dev:latest                                                                                                                                                       0.0s
$ docker run --publish 1313:1313 --detach --mount src="$(pwd)",target=/home/docsy/app,type=bind …
```
=> Dockerfile + docker-compose.yaml build/running

README.md
The PR adds a troubleshooting section to the README.
It also adds a solution for the following commonly faced error:
```
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68" not found in file cache
```
I also logged an issue for the same problem: #100 
Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>
=> Add a troubleshooting section.

README.md
Official hugo docs dropped themes documentation in favour of modules documentation. I think it's time to move on to modules 😉.
=> README.md: correct dead link (installing/using themes)

config.toml
When using docsy as hugo module, inside `config.toml`, the language settings must declared prior to the `[module]` section. If you do not obey this load order, you are running in trouble.
This PR moves the language settings inside `config.toml` up to the top of the file. By doing so, we are ensuring a smooth transition for users that want to pull the docsy theme into the example site as a hugo module.
=> config.toml: change order of  language settings and theme/module declaration

config.toml
I don't think taxonomyCloud has a language, and I think they need to have the same length, so I think this is what was intended.
=> config.toml: comment typo: s/lang/length

config.toml, go.mod, go.sum, netlify.toml
This PR is closely associated [PR 801](https://github.com/google/docsy/pull/801#issue-1076871740), which tries to bring hugo modules to docsy theme.
The goal is to make use of the example site as easy as possible:
```
git clone https://github.com/google/docsy-example
cd docsy-example
hugo server
```
No fiddling around with gut submodules any more.
Please note that this PR is not fully ready for review yet, inside my go.mod, I'm missing the commit hash of the docsy repo once [PR 801](https://github.com/google/docsy/pull/801#issue-1076871740) is applied. Or I can refer to commit in the branch `modules` (to be newly created in the Docsy repo).
=> Make docsy example site use docsy theme as hugo module

go.mod, go.sum
=> docsy as module: refer to current HEAD of repo

go.mod
This PR brings the example site to version `v0.2.0` of the docsy theme, to be released soon. This PR should be merged immediately before or after `v0.2.0` was released.
=> Update example site to docsy theme v0.2.0

README.md
=> README.md: reflect changes due to use of theme as hugo module

config.toml, netlify.toml
As of version 0.100, hugo [dropped support](https://github.com/gohugoio/hugo/issues/9944) for Blackfriday markdown engine.
This PR makes changes to `config.toml` to reflect this.
=> config.toml: remove section [blackfriday] (unsupported)

config.toml, netlify.toml
When running the example site with hugo v0.112, a bunch of warnings is emitted:
```
WARN 2023/05/23 22:02:22 config: languages.no.description: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.no.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
WARN 2023/05/23 22:02:22 config: languages.no.time_format_default: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.no.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
WARN 2023/05/23 22:02:22 config: languages.no.time_format_blog: custom params on the language top level is deprecated and will be removed in a future release. …
```
=> Fix: remove warnings emitted from hugo v0.112

README.md, go.mod, go.sum, netlify.toml
Update the theme, the README file, and the hugo and go versions.
=> Update docsy theme to docsy v0.6.0

config.toml, netlify.toml, package.json
- Contributes to #207
- Upgrades to latest Hugo
- Renames default branch to `main` in config file
- Moves `title` under `languages.<lang>.params` so that `og:site_name` gets generated
- Best reviewed by ignoring whitespace changes
=> Set version to 0.7.0-dev, adjust default branch, and more

netlify.toml, package.json
- Contributes to #207
- Drop NPM `prepare` command since this site is build using Hugo modules
We now have easily accessible build previews!
> <img width="842" alt="image" src="https://github.com/google/docsy-example/assets/4140793/a5803131-663e-4526-a865-d152019ac0e6">
=> Netlify config: drop NPM prepare command

.vscode/settings.json, README.md, package.json
- Contributes to #216
- Drops `--themesDir` from `_hugo` script
- Tweaks readme, mainly fixing code-block language
- Adds a cSpell dictionary under VSCode settings
=> Drop themesDir from NPM script, tweak README, add dict

content/en/_index.html, content/fa/_index.html
- Fixes layout collapses in the top page
- Contributes to #207
=> Fix layout collapses of features

config.yaml
- Closes #228
- E.g., when using Hugo 0.109:
```console
$ npx hugo
WARN 2023/06/26 16:59:04 Module "project" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Start building sites … 
hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended darwin/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio
Error: Error building site: "/Users/chalin/git/lf/docsy/docsy-example/content/en/_index.md:5:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
Total in 21 ms
```
- Adding this config file does not (seem to) affect builds using Hugo 0.110.0 and later (as we can see from the build of this PR).
/cc @geriom
=> Add a error-detection config for older versions of Hugo

README.md, go.mod, go.sum, hugo.toml
This PR update the example site to the latest docsy development version `v0.7.3-dev`.
=> Update example site to latest docsy development version

go.mod, go.sum, hugo.toml
- Upgrades Docsy so that we can test new GA4 and page feedback features
- Contributes to prep for testing of https://github.com/google/docsy/issues/1302
=> Upgrade Docsy to 0.7.3-dev 2023-11-14 revision

Dockerfile, docker-compose.yaml
The docker container we refer to is not well maintained any more. This PR changes to another container that has latest hugo version `0.120.4`.
=> Docker files: change to another provider

hugo.toml
A minor change that allow clicking the URL from console.
```sh
hugo server
...
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
```
With this PR:
```sh
hugo server
...
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
```
=> Change the default baseURL as example.org

go.mod, go.sum, netlify.toml, package.json
With this PR merged, the example site can be previewed with latest hugo version v0.125.3 again.
=> docsy theme used: Bump to current head of theme repo

hugo.toml, package.json
- Prep for #295
- Declares `fa` as an `rtl` language. Note that this has no effect on the generated files currently, since Docsy doesn't recognize RTL language (yet)
- Minor NPM script tweak
=> Specify `fa` as `rtl` lang + NPM script tweak

hugo.toml
=> Update hugo.toml in prep for conversion

hugo.toml
- Contributes to #226
- Reverts `taxonomyCloud` array element order change of #297
=> Update hugo.toml: revert taxonomyCloud elt order

go.mod, go.sum, hugo.yaml
- Contributes to #295
- Upgrades Docsy to v0.10.0-7-g3674691, which includes RTL support
- Teaks the Persian config parameters.
**Preview**: https://deploy-preview-300--goldydocs.netlify.app/fa/
/cc @google/docsy-approvers
=> Upgrade Docsy to include RTL support + tweak `fa` config

go.mod, go.sum
- Contributes to #295
- **Preview**: https://deploy-preview-305--goldydocs.netlify.app/fa/
This illustrates the fix to https://github.com/google/docsy/issues/2011:
> <img width="1009" alt="image" src="https://github.com/google/docsy-example/assets/4140793/e7fa60fa-9f44-4a7b-8659-b19bea8ba20d">
=> Upgrade Docsy to v0.10.0-12-g333c2f8

go.mod, go.sum, package.json
- Contributes to #295
- **Preview**: https://deploy-preview-322--goldydocs.netlify.app/fa/docs/
Illustrates that the top-nav and footer are better than ever, in particular that the following have been fixed:
- https://github.com/google/docsy/issues/2005
- https://github.com/google/docsy/issues/2011
> <img width="1036" alt="image" src="https://github.com/user-attachments/assets/d1450a82-b1d4-4410-901c-ff604889c942">
Contrast this with the previous iteration, via #305:
- https://deploy-preview-305--goldydocs.netlify.app/fa/docs/
=> Upgrade Docsy to v0.10.0-33-gfe0d785, add rtlcss pkg

content/fa/_index.md, content/no/_index.html
- Before this change the `fa` index page's "Learn more" button would link to the `en` docs page. This PR fixes that uniformly for `fa` and `no` pages, without the need to resort to the use of `relref`.
- Contributes to #295
- **Preview**: https://deploy-preview-325--goldydocs.netlify.app/fa/
=> [i18n] Ensure that "Learn more" of non-en index links to same-language docs

content/en/community/_index.md
Otherwise, this can prevent the page description from being automatically set to a reasonable value -- because the page content isn't empty, but the content isn't meaningful.
=> Community page cleanup: move comment into front matter

README.md, hugo-disabled.toml
This PR adds the `proxy` attribute to the module configuration, thus alleviating the use of a proxy.
=> Module config: mention possible need for proxy setting

go.mod, go.sum, layouts/_default/_markup/render-heading.html, package.json
This PR Bump to latest docsy theme so that example site can use latest hugo version 0.146.
This PR closes #354.
=> Bump to latest docsy theme so that we eventually can use latest hugo version 0.146

hugo-disabled.toml, hugo.yaml
**Reproduction:**:
Comment out this line in `hugo.yaml`:
```
disableKinds = ["taxonomy", "taxonomyTerm"]
```
Now when previewing the site, a warning appears:
```
WARN  DEPRECATED: Kind "taxonomyterm" used in disableKinds is deprecated, use "taxonomy" instead.
```
This PR fixes that issue.
=> Fix warning about deprecated kind 'taxonomyterm' in disableKinds

package.json
- Closes #386 (which seems to be blocked), by superseding it.
- The bot upgrade PR was block/failing (as was this one originally), because of #388
=> Update packages, Hugo to 0.150.1
